name: Swift

on:
  push:
    branches: [ main, develop ]

jobs:
  build:
    name: Build and Test
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/cache@v3
      with:
        path: /Users/runner/Library/Developer/Xcode/DerivedData/**/SourcePackages/checkouts 
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
    - name: Write config.swift
      run: |
        echo "${{ secrets.CONFIG_SWIFT }}" > Sources/AoC/config.swift
    - name: Run tests
      run: |
        xcodebuild test -scheme AoC -destination platform="macOS"
    - name: Codecov
      uses: codecov/codecov-action@v3
