name: Swift

on:
  push:
    branches: [ main, develop ]

jobs:
  build:
    name: Build and Test
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Write config.swift
      run: |
        echo "${{ secrets.CONFIG_SWIFT }}" > Sources/AoC/config.swift
    - name: Run tests
      run: |
        xcodebuild test -scheme AoC -destination platform="macOS"
    - name: Codecov
      uses: codecov/codecov-action@v1.2.1
